# Definiert das Deployment für Nextcloud
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deploy # Name des Deployments
  namespace: nextcloud # Namespace, in dem das Deployment erstellt wird
spec:
  replicas: 1 # Anzahl der Pod-Replikationen
  selector:
    matchLabels:
      app: nextcloud # Selektiert die Pod-Instanzen anhand der Label
  template:
    metadata:
      labels:
        app: nextcloud # Labels für den Pod
    spec:
      # Definiert das Persistent Volume für Nextcloud
      volumes:
      - name: nextcloud-storage2 # Name vom PVC
        persistentVolumeClaim:
          claimName: nextcloud-pvc2 # Name vom Persistent Volume Claim
      containers:
      - name: nextcloud # Name des Containers
        image: nextcloud:latest # Name des Docker-Images und dessen Tag
        imagePullPolicy: Always # Pull-Policy für das Docker-Image
        ports:
        - containerPort: 80 # Port-Nummer
        env:
        # Setzt die Umgebungsvariablen für die Konfiguration von Nextcloud
        - name: PGID # Name der Gruppe, die für den Container verwendet werden soll
          value: "100"
        - name: PUID # Name des Benutzers, der für den Container verwendet werden soll
          value: "1041"
        - name: TZ # Zeitzone für den Container
          value: Europe/Zurich
        volumeMounts:
        # Mountet das Persistent Volume für die Konfigurationsdateien von Nextcloud
        - mountPath: /config # Mount-Pfad im Container
          name: nextcloud-storage2 # Name vom PVC
          subPath: config # Sub-Path innerhalb des Volumes
        # Mountet das Persistent Volume für die Daten von Nextcloud
        - mountPath: /var/www/html/data # Mount-Pfad im Container
          name: nextcloud-storage2 # Name vom PVC
          subPath: data # Sub-Path innerhalb des Volumes

# Definiert den Service für Nextcloud
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service # Name des Services
  namespace: nextcloud # Namespace, in dem der Service erstellt wird
spec:
  selector:
    app: nextcloud # Selektiert die Pod-Instanzen anhand der Label
  ports:
  - name: http # Name des Ports
    port: 80 # Port-Nummer
    targetPort: 80 # Port-Nummer, auf den der Service verweist
  type: LoadBalancer # Typ des Services
  loadBalancerIP: 10.1.1.1 #Die externe IP-Adresse des Load Balancers
  clusterIP: 10.152.183.222 #Die interne IP-Adresse des Services im Cluster
